runtime: python312
entrypoint: gunicorn -b :$PORT run:app

beta_settings:
   cloud_sql_instances: "restaurantapp-483917:europe-west2:restaurant-postgres" 

env_variables:
   DB_NAME: "restaurantdb"
   DB_USER: "mattdev"
   INSTANCE_CONNECTION_NAME: "restaurantapp-483917:europe-west2:restaurant-postgres"
   GCS_BUCKET: " menu-images-restaurantapp-sd"
   ORDER_CONFIRMATION_URL: "https://europe-west1-restaurantapp-483917.cloudfunctions.net/order_confirmation"


